# Stage build
FROM golang:1.23-alpine AS builder
WORKDIR /app

# Copy dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy all source
COPY . .

# Build
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ingestion-service main.go db.go processor.go

# Final minimal image
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/ingestion-service .

RUN apk --no-cache add ca-certificates

# Optional healthcheck
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD ./ingestion-service --health || exit 1

CMD ["./ingestion-service"]
